apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: spicelab
  namespace: spicelab
  labels:
    app.kubernetes.io/name: spicelab
    app.kubernetes.io/component: server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spicelab
      app.kubernetes.io/component: server
