apiVersion: v1
kind: ServiceAccount
metadata:
  name: spicelab
  namespace: spicelab
  labels:
    app.kubernetes.io/name: spicelab
    app.kubernetes.io/component: server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spicelab
  namespace: spicelab
  labels:
    app.kubernetes.io/name: spicelab
spec:
  rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spicelab
  namespace: spicelab
  labels:
    app.kubernetes.io/name: spicelab
spec:
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: spicelab
  subjects:
  - kind: ServiceAccount
    name: spicelab
    namespace: spicelab
