apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spicelab
  namespace: spicelab
  labels:
    app.kubernetes.io/name: spicelab
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spicelab
      app.kubernetes.io/component: server
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - spicelab
